version: '3'

services:
  serv:
    hostname: "test"
    image: ghcr.io/lidory/learnpackages/my_image:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile.hello-world
    # image: my_image