name: Push Docker Image
decription: 'Build and push to GitHub package a specified docker image'


inputs:
  docker-file-path: 
    description: 'Dockerfile path to build the image from.'
    required: true
  image-name: 
    description: 'The name of the image that will be generated'
    required: true
  # Since we can't access the repository env variables from inside an action
  #   we provide them as variables here.
  username: 
    description: 'The github user name. Should ALWAYS be: github.actor'
    required: true
  password: 
    description: 'The github user name. Should ALWAYS be: secrets.GITHUB_TOKEN'
    required: true
  context: 
    description: 'Context value for the docker build operation'
    default: .

runs:
  using: 'composite'
  steps:
    - uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        # The GitHub package regitry URL
        registry: ghcr.io
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ghcr.io/${{ github.repository }}/${{ inputs.image-name}}
        github-token: ${{ inputs.password }}
    - run: |
          string_to_split=${{ steps.meta.outputs.tags }}
          IFS=':' read -ra split_string <<< "$string_to_split"
          echo "${split_string[0]}"
      shell: bash
    - uses: docker/build-push-action@v3
      with:
        push: true
        file: "${{ inputs.docker-file-path}}"
        tags: "ghcr.io/lidory/learnpackages/img1"
        context: ${{ inputs.context }}
