name: Publish Tests container Docker Image

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - 'ttt/test.sh'
      - '**Dockerfile**'
  pull_request:
    types: [ opened, reopened, synchronize ]

      
jobs:
  push_to_registry:
    name: Push Docker image to GitHub registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - if: "!(contains(steps.files.outputs.changes, 'Dockerfile') || contains(steps.files.outputs.changes, 'ttt/test.sh'))"
        run: exit 0
        shell: bash
      # Example 1
      - id: files
        uses: ./.github/actions/list_changed_files
      
      - name: test
        run: echo ${{ steps.files.outputs.changes }}
      
      - run: echo "TEST=3.8" >> $GITHUB_ENV

      - name: Upload Image 1
        uses: ./.github/actions/upload_image
        # if: |
        #   contains(steps.files.outputs.changes, 'Dockerfile.hello-world2') || contains(steps.files.outputs.changes, 'ttt/test.sh')
        with:
          image-name: img1
          docker-file-path: Dockerfile.hello-world2
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Upload Image 2
      #   uses: ./.github/actions/upload_image
      #   if: contains(steps.changed-files.outputs.all_changed_files, 'Dockerfile.hello-world2')
      #   with:
      #     image-name: my_image2
      #     docker-file-path: Dockerfile.hello-world2
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      