name: Publish Tests container Docker Image

on:
  # Compare the preceeding commit of main -> to the current commit of the main branch.
  # (Note: To compare changes between the last pushed commit to the remote main branch set `since_last_remote_commit: true`)
  push:
    branches:
      - main
  # Compare the last commit of main -> to the current commit of a PR branch.
  # (Note: To compare changes between the last pushed commit to the remote PR branch set `since_last_remote_commit: true`)
  pull_request:
    branches:
      - main
      
jobs:
  push_to_registry:
    name: Push Docker image to GitHub registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      # Example 1
      - id: files
        name: (CI) Dependencies update check
        run: |
          current_commit=`git log -n 1 --pretty=format:%H`
          changed_files=`git diff-tree --no-commit-id --name-only -r $current_commit`
          changed_files="${changed_files//'%'/', '}"
          changed_files="${changed_files//$'\n'/', '}"
          changed_files="${changed_files//$'\r'/', '}"
          echo "all=$changed_files" >> $GITHUB_OUTPUT

      - name: Upload Image 1
        uses: ./.github/actions/upload_image
        if: contains(steps.files.outputs.all, 'ttt/Dockerfile.hello-world')
        with:
          image-name: my_image
          docker-file-path: ttt/Dockerfile.hello-world
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          context: ./ttt

      # - name: Upload Image 2
      #   uses: ./.github/actions/upload_image
      #   if: contains(steps.changed-files.outputs.all_changed_files, 'Dockerfile.hello-world2')
      #   with:
      #     image-name: my_image2
      #     docker-file-path: Dockerfile.hello-world2
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      