name: Publish Tests container Docker Image

on:
  workflow_dispatch: {}

jobs:
  push_to_registry:
    name: Push Docker image to GitHub registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # In order to access the local action
      - name: Upload Image 1
        uses: ./.github/actions/upload_image
        with:
          image-name: my_image
          docker-file-path: Dockerfile.hello-world
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Image 2
        uses: ./.github/actions/upload_image
        with:
          image-name: my_image2
          docker-file-path: Dockerfile.hello-world2
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      