name: Publish Tests container Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  push_to_registry:
    name: Push Docker image to GitHub registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # In order to access the local action
        with:
          fetch-depth: 0
      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v35
      - name: Upload Image 1
        uses: ./.github/actions/upload_image
        # if: 'Dockerfile.hello-world' in steps.changed-files.outputs.all_changed_files
        with:
          image-name: my_image
          docker-file-path: Dockerfile.hello-world
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Image 2
        uses: ./.github/actions/upload_image
        # if: 'Dockerfile.hello-world2' in steps.changed-files.outputs.all_changed_files
        with:
          image-name: my_image2
          docker-file-path: Dockerfile.hello-world2
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      