name: Publish Tests container Docker Image

on:
  workflow_dispatch: {}

jobs:
  push_to_registry:
    name: Push Docker image to GitHub registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Upload Doker Image
        uses: ./.github/actions/build_push_docker_image
        with:
          image-name: my_image
          docker-file-path: Dockerfile.hello-world
      