name: run test

on:
  workflow_dispatch: {}

jobs:
 end2end_test:
   name: test
   runs-on: ubuntu-latest
    permissions:
      packages: read
   steps:
    - name: Checkout
      uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume
    - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: run
      run: |
        docker-compose -f docker-compose.yml up

