name: run test

on:
  workflow_dispatch: {}

jobs:
 end2end_test:
   name: test
   runs-on: ubuntu-latest
   permissions:
      packages: write
   container:
     image: ghcr.io/lidory/learnpackages/img1:main
     credentials:
       username: ${{ github.actor }}
       password: ${{ secrets.GITHUB_TOKEN }}
   steps:
    - name: Checkout
      uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: run
      run: |
        docker-compose -f docker-compose.yml up
    # - uses: ./.github/actions/set_vars
    # - name: Analysing the code with mypy
    #   run: |
    #     mypy . --show-error-codes
    #     echo "${{ env.TEST }}"
    #     echo $HOME
        