name: run test

on:
  workflow_dispatch: {}

jobs:
 end2end_test:
   name: test
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume
    - name: run
      run: |
        docker-compose -f docker-compose.yml up

